deps_config := \
	/home/riscv/zephyr/boards/arc/arduino_101_sss/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arc/em_starterkit/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arc/panther_ss/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arc/quark_se_c1000_ss_devboard/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/96b_carbon/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/96b_carbon_nrf51/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/96b_nitrogen/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/arduino_101_ble/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/arduino_due/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/bbc_microbit/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/cc2650_sensortag/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/cc3200_launchxl/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/cc3220sf_launchxl/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/curie_ble/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/disco_l475_iot1/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/frdm_k64f/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/frdm_kl25z/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/frdm_kw41z/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/hexiwear_k64/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/hexiwear_kw40z/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/mps2_an385/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nrf51_blenano/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nrf51_pca10028/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nrf51_vbluno51/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nrf52840_pca10056/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nrf52_blenano2/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nrf52_pca10040/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nucleo_f103rb/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nucleo_f334r8/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nucleo_f401re/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nucleo_f411re/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nucleo_f412zg/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nucleo_f413zh/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nucleo_l432kc/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/nucleo_l476rg/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/olimex_stm32_e407/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/olimexino_stm32/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/qemu_cortex_m3/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/quark_se_c1000_ble/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/sam4s_xplained/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/sam_e70_xplained/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/stm3210c_eval/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/stm32373c_eval/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/stm32_min_dev/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/stm32_mini_a15/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/stm32f3_disco/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/stm32f469i_disco/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/stm32f4_disco/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/stm32l496g_disco/Kconfig.defconfig \
	/home/riscv/zephyr/boards/arm/v2m_beetle/Kconfig.defconfig \
	/home/riscv/zephyr/boards/nios2/altera_max10/Kconfig.defconfig \
	/home/riscv/zephyr/boards/nios2/qemu_nios2/Kconfig.defconfig \
	/home/riscv/zephyr/boards/riscv32/artix7_ppu/Kconfig.defconfig \
	/home/riscv/zephyr/boards/riscv32/qemu_riscv32/Kconfig.defconfig \
	/home/riscv/zephyr/boards/riscv32/zedboard_pulpino/Kconfig.defconfig \
	/home/riscv/zephyr/boards/x86/arduino_101/Kconfig.defconfig \
	/home/riscv/zephyr/boards/x86/galileo/Kconfig.defconfig \
	/home/riscv/zephyr/boards/x86/minnowboard/Kconfig.defconfig \
	/home/riscv/zephyr/boards/x86/panther/Kconfig.defconfig \
	/home/riscv/zephyr/boards/x86/qemu_x86/Kconfig.defconfig \
	/home/riscv/zephyr/boards/x86/quark_d2000_crb/Kconfig.defconfig \
	/home/riscv/zephyr/boards/x86/quark_se_c1000_devboard/Kconfig.defconfig \
	/home/riscv/zephyr/boards/x86/tinytile/Kconfig.defconfig \
	/home/riscv/zephyr/boards/xtensa/esp32/Kconfig.defconfig \
	/home/riscv/zephyr/boards/xtensa/qemu_xtensa/Kconfig.defconfig \
	/home/riscv/zephyr/boards/xtensa/xt-sim/Kconfig.defconfig \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_x1000/Kconfig.defconfig.quark_x1000 \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_se/Kconfig.defconfig.curie \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_se/Kconfig.defconfig.quark_se_c1000 \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_d2000/Kconfig.defconfig.quark_d2000 \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_d2000/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_se/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_x1000/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/fe310/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/riscv32-qemu/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.defconfig.cc3200 \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.defconfig.cc3220sf \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/cc2650/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l432xx \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l475xg \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l476xx \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l496xx \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f401xe \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f407xx \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f411xe \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f412zg \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f413xx \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f429xx \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f469xi \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f3/Kconfig.defconfig.stm32f303xc \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f3/Kconfig.defconfig.stm32f334x8 \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f3/Kconfig.defconfig.stm32f373xc \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f103xx \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f107xc \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f3/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kwx/Kconfig.defconfig.mkw40z4 \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kwx/Kconfig.defconfig.mkw41z4 \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kl2x/Kconfig.defconfig.mkl25z4 \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/k6x/Kconfig.defconfig.mk64f12 \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/k6x/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kl2x/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kwx/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.nrf52832_QFAA \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.nrf52840_QIAA \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAA \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAB \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAC \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/sam3x/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/sam4s/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/same70/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/arm/mps2/Kconfig.defconfig.mps2_an385 \
	/home/riscv/zephyr/arch/arm/soc/arm/beetle/Kconfig.defconfig.beetle_r0 \
	/home/riscv/zephyr/arch/arm/soc/arm/beetle/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arm/soc/arm/mps2/Kconfig.defconfig.series \
	/home/riscv/zephyr/arch/arc/soc/em11d/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arc/soc/em7d/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arc/soc/em9d/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arc/soc/quark_se_c1000_ss/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arm/soc/arm/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arm/soc/ti_lm3s6965/Kconfig.defconfig \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/Kconfig.defconfig \
	/home/riscv/zephyr/arch/nios2/soc/nios2-qemu/Kconfig.defconfig \
	/home/riscv/zephyr/arch/nios2/soc/nios2f-zephyr/Kconfig.defconfig \
	/home/riscv/zephyr/arch/riscv32/soc/ppu/Kconfig.defconfig \
	/home/riscv/zephyr/arch/riscv32/soc/pulpino/Kconfig.defconfig \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/Kconfig.defconfig \
	/home/riscv/zephyr/arch/x86/soc/atom/Kconfig.defconfig \
	/home/riscv/zephyr/arch/x86/soc/ia32/Kconfig.defconfig \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/D_108mini/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/D_212GP/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/D_233L/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/XRC_D2PM_5swIrq/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/XRC_FUSION_AON_ALL_LM/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/esp32/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/hifi2_std/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/hifi3_bd5/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/hifi3_bd5_call0/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/hifi4_bd7/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/hifi_mini/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/hifi_mini_4swIrq/Kconfig.defconfig \
	/home/riscv/zephyr/arch/xtensa/soc/sample_controller/Kconfig.defconfig \
	/home/riscv/zephyr/tests/ztest/Kconfig \
	/home/riscv/zephyr/tests/Kconfig \
	/home/riscv/zephyr/ext/debug/segger/Kconfig \
	/home/riscv/zephyr/ext/debug/Kconfig \
	/home/riscv/zephyr/ext/fs/fat/Kconfig \
	/home/riscv/zephyr/ext/fs/Kconfig \
	/home/riscv/zephyr/ext/lib/crypto/mbedtls/Kconfig \
	/home/riscv/zephyr/ext/lib/crypto/tinycrypt/Kconfig \
	/home/riscv/zephyr/ext/lib/crypto/Kconfig \
	/home/riscv/zephyr/ext/hal/ti/simplelink/Kconfig \
	/home/riscv/zephyr/ext/hal/ti/cc3200sdk/Kconfig \
	/home/riscv/zephyr/ext/hal/st/stm32cube/Kconfig \
	/home/riscv/zephyr/ext/hal/qmsi/Kconfig \
	/home/riscv/zephyr/ext/hal/nxp/mcux/Kconfig \
	/home/riscv/zephyr/ext/hal/nordic/Kconfig \
	/home/riscv/zephyr/ext/hal/cmsis/Kconfig \
	/home/riscv/zephyr/ext/hal/atmel/asf/Kconfig \
	/home/riscv/zephyr/ext/hal/Kconfig \
	/home/riscv/zephyr/ext/Kconfig \
	/home/riscv/zephyr/subsys/usb/class/Kconfig \
	/home/riscv/zephyr/subsys/usb/Kconfig \
	/home/riscv/zephyr/subsys/shell/modules/Kconfig \
	/home/riscv/zephyr/subsys/shell/Kconfig \
	/home/riscv/zephyr/subsys/net/lib/app/Kconfig \
	/home/riscv/zephyr/subsys/net/lib/http/Kconfig \
	/home/riscv/zephyr/subsys/net/lib/mqtt/Kconfig \
	/home/riscv/zephyr/subsys/net/lib/dns/Kconfig \
	/home/riscv/zephyr/subsys/net/lib/zoap/Kconfig \
	/home/riscv/zephyr/subsys/net/lib/sockets/Kconfig \
	/home/riscv/zephyr/subsys/net/lib/Kconfig \
	/home/riscv/zephyr/subsys/net/ip/Kconfig.stats \
	/home/riscv/zephyr/subsys/net/ip/Kconfig.rpl \
	/home/riscv/zephyr/subsys/net/ip/Kconfig.mgmt \
	/home/riscv/zephyr/subsys/net/ip/l2/ieee802154/Kconfig.radio \
	/home/riscv/zephyr/subsys/net/ip/l2/ieee802154/Kconfig \
	/home/riscv/zephyr/subsys/net/ip/l2/Kconfig \
	/home/riscv/zephyr/subsys/net/ip/Kconfig.stack \
	/home/riscv/zephyr/subsys/net/ip/Kconfig.ipv4 \
	/home/riscv/zephyr/subsys/net/ip/Kconfig.ipv6 \
	/home/riscv/zephyr/subsys/net/ip/Kconfig.debug \
	/home/riscv/zephyr/subsys/net/ip/Kconfig \
	/home/riscv/zephyr/subsys/net/Kconfig \
	/home/riscv/zephyr/subsys/logging/Kconfig \
	/home/riscv/zephyr/subsys/fs/Kconfig \
	/home/riscv/zephyr/subsys/disk/Kconfig \
	/home/riscv/zephyr/subsys/debug/Kconfig \
	/home/riscv/zephyr/subsys/cpp/Kconfig \
	/home/riscv/zephyr/subsys/console/Kconfig \
	/home/riscv/zephyr/subsys/bluetooth/shell/Kconfig \
	/home/riscv/zephyr/subsys/bluetooth/controller/Kconfig \
	/home/riscv/zephyr/subsys/bluetooth/host/Kconfig \
	/home/riscv/zephyr/subsys/bluetooth/common/Kconfig \
	/home/riscv/zephyr/subsys/bluetooth/Kconfig \
	/home/riscv/zephyr/subsys/Kconfig \
	/home/riscv/zephyr/lib/json/Kconfig \
	/home/riscv/zephyr/lib/libc/Kconfig \
	/home/riscv/zephyr/lib/Kconfig \
	/home/riscv/zephyr/misc/Kconfig \
	/home/riscv/zephyr/drivers/display/Kconfig \
	/home/riscv/zephyr/drivers/crypto/Kconfig.ataes132a \
	/home/riscv/zephyr/drivers/crypto/Kconfig \
	/home/riscv/zephyr/drivers/usb/device/Kconfig \
	/home/riscv/zephyr/drivers/usb/Kconfig \
	/home/riscv/zephyr/drivers/dma/Kconfig \
	/home/riscv/zephyr/drivers/counter/Kconfig.dtmr_cmsdk_apb \
	/home/riscv/zephyr/drivers/counter/Kconfig.tmr_cmsdk_apb \
	/home/riscv/zephyr/drivers/counter/Kconfig.qmsi \
	/home/riscv/zephyr/drivers/counter/Kconfig \
	/home/riscv/zephyr/drivers/sensor/tmp112/Kconfig \
	/home/riscv/zephyr/drivers/sensor/tmp007/Kconfig \
	/home/riscv/zephyr/drivers/sensor/th02/Kconfig \
	/home/riscv/zephyr/drivers/sensor/sx9500/Kconfig \
	/home/riscv/zephyr/drivers/sensor/sht3xd/Kconfig \
	/home/riscv/zephyr/drivers/sensor/nrf5/Kconfig \
	/home/riscv/zephyr/drivers/sensor/mpu6050/Kconfig \
	/home/riscv/zephyr/drivers/sensor/mcp9808/Kconfig \
	/home/riscv/zephyr/drivers/sensor/max44009/Kconfig \
	/home/riscv/zephyr/drivers/sensor/max30101/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lsm9ds0_mfd/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lsm9ds0_gyro/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lsm6dsl/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lsm6ds0/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lps25hb/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lps22hb/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lis3mdl/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lis3dh/Kconfig \
	/home/riscv/zephyr/drivers/sensor/lis2dh/Kconfig \
	/home/riscv/zephyr/drivers/sensor/isl29035/Kconfig \
	/home/riscv/zephyr/drivers/sensor/hts221/Kconfig \
	/home/riscv/zephyr/drivers/sensor/hp206c/Kconfig \
	/home/riscv/zephyr/drivers/sensor/hmc5883l/Kconfig \
	/home/riscv/zephyr/drivers/sensor/hdc1008/Kconfig \
	/home/riscv/zephyr/drivers/sensor/fxos8700/Kconfig \
	/home/riscv/zephyr/drivers/sensor/fxas21002/Kconfig \
	/home/riscv/zephyr/drivers/sensor/dht/Kconfig \
	/home/riscv/zephyr/drivers/sensor/bmi160/Kconfig \
	/home/riscv/zephyr/drivers/sensor/bmg160/Kconfig \
	/home/riscv/zephyr/drivers/sensor/bme280/Kconfig \
	/home/riscv/zephyr/drivers/sensor/bmc150_magn/Kconfig \
	/home/riscv/zephyr/drivers/sensor/bma280/Kconfig \
	/home/riscv/zephyr/drivers/sensor/ak8975/Kconfig \
	/home/riscv/zephyr/drivers/sensor/adxl362/Kconfig \
	/home/riscv/zephyr/drivers/sensor/Kconfig \
	/home/riscv/zephyr/drivers/flash/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/flash/Kconfig \
	/home/riscv/zephyr/drivers/aio/Kconfig \
	/home/riscv/zephyr/drivers/ipm/Kconfig \
	/home/riscv/zephyr/drivers/clock_control/Kconfig.beetle \
	/home/riscv/zephyr/drivers/clock_control/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/clock_control/Kconfig.quark_se \
	/home/riscv/zephyr/drivers/clock_control/Kconfig.nrf5 \
	/home/riscv/zephyr/drivers/clock_control/Kconfig \
	/home/riscv/zephyr/drivers/watchdog/Kconfig.sam \
	/home/riscv/zephyr/drivers/watchdog/Kconfig.cmsdk_apb \
	/home/riscv/zephyr/drivers/watchdog/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/watchdog/Kconfig.qmsi \
	/home/riscv/zephyr/drivers/watchdog/Kconfig \
	/home/riscv/zephyr/drivers/rtc/Kconfig \
	/home/riscv/zephyr/drivers/adc/Kconfig \
	/home/riscv/zephyr/drivers/pinmux/Kconfig.ppu \
	/home/riscv/zephyr/drivers/pinmux/Kconfig.cc2650 \
	/home/riscv/zephyr/drivers/pinmux/Kconfig.fe310 \
	/home/riscv/zephyr/drivers/pinmux/Kconfig.beetle \
	/home/riscv/zephyr/drivers/pinmux/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/pinmux/Kconfig.mcux \
	/home/riscv/zephyr/drivers/pinmux/dev/Kconfig \
	/home/riscv/zephyr/drivers/pinmux/Kconfig \
	/home/riscv/zephyr/drivers/pwm/Kconfig.nrf5_sw \
	/home/riscv/zephyr/drivers/pwm/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/pwm/Kconfig.k64 \
	/home/riscv/zephyr/drivers/pwm/Kconfig.dw \
	/home/riscv/zephyr/drivers/pwm/Kconfig.qmsi \
	/home/riscv/zephyr/drivers/pwm/Kconfig.pca9685 \
	/home/riscv/zephyr/drivers/pwm/Kconfig \
	/home/riscv/zephyr/drivers/i2c/Kconfig.ppu \
	/home/riscv/zephyr/drivers/i2c/Kconfig.gpio \
	/home/riscv/zephyr/drivers/i2c/Kconfig.sbcon \
	/home/riscv/zephyr/drivers/i2c/Kconfig \
	/home/riscv/zephyr/drivers/spi/Kconfig.ppu \
	/home/riscv/zephyr/drivers/spi/Kconfig.nrf5 \
	/home/riscv/zephyr/drivers/spi/Kconfig.mcux_dspi \
	/home/riscv/zephyr/drivers/spi/Kconfig.dw \
	/home/riscv/zephyr/drivers/spi/Kconfig \
	/home/riscv/zephyr/drivers/shared_irq/Kconfig \
	/home/riscv/zephyr/drivers/gpio/Kconfig.cc2650 \
	/home/riscv/zephyr/drivers/gpio/Kconfig.fe310 \
	/home/riscv/zephyr/drivers/gpio/Kconfig.ppu \
	/home/riscv/zephyr/drivers/gpio/Kconfig.pulpino \
	/home/riscv/zephyr/drivers/gpio/Kconfig.cc32xx \
	/home/riscv/zephyr/drivers/gpio/Kconfig.cmsdk_ahb \
	/home/riscv/zephyr/drivers/gpio/Kconfig.nrf5 \
	/home/riscv/zephyr/drivers/gpio/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/gpio/Kconfig.atmel_sam3 \
	/home/riscv/zephyr/drivers/gpio/Kconfig.mmio32 \
	/home/riscv/zephyr/drivers/gpio/Kconfig.mcux \
	/home/riscv/zephyr/drivers/gpio/Kconfig.sch \
	/home/riscv/zephyr/drivers/gpio/Kconfig.qmsi \
	/home/riscv/zephyr/drivers/gpio/Kconfig.pcal9535a \
	/home/riscv/zephyr/drivers/gpio/Kconfig.dw \
	/home/riscv/zephyr/drivers/gpio/Kconfig \
	/home/riscv/zephyr/drivers/pci/Kconfig \
	/home/riscv/zephyr/drivers/grove/Kconfig \
	/home/riscv/zephyr/drivers/random/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/random/Kconfig.mcux \
	/home/riscv/zephyr/drivers/random/Kconfig \
	/home/riscv/zephyr/drivers/timer/Kconfig \
	/home/riscv/zephyr/drivers/interrupt_controller/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/interrupt_controller/Kconfig \
	/home/riscv/zephyr/drivers/serial/Kconfig.esp32 \
	/home/riscv/zephyr/drivers/serial/Kconfig.fe310 \
	/home/riscv/zephyr/drivers/serial/Kconfig.riscv_qemu \
	/home/riscv/zephyr/drivers/serial/Kconfig.cmsdk_apb \
	/home/riscv/zephyr/drivers/serial/Kconfig.cc32xx \
	/home/riscv/zephyr/drivers/serial/Kconfig.altera_jtag \
	/home/riscv/zephyr/drivers/serial/Kconfig.nrf5 \
	/home/riscv/zephyr/drivers/serial/Kconfig.stm32 \
	/home/riscv/zephyr/drivers/serial/Kconfig.qmsi \
	/home/riscv/zephyr/drivers/serial/Kconfig.uart_sam \
	/home/riscv/zephyr/drivers/serial/Kconfig.usart_sam \
	/home/riscv/zephyr/drivers/serial/Kconfig.atmel_sam3 \
	/home/riscv/zephyr/drivers/serial/Kconfig.nsim \
	/home/riscv/zephyr/drivers/serial/Kconfig.stellaris \
	/home/riscv/zephyr/drivers/serial/Kconfig.mcux_lpuart \
	/home/riscv/zephyr/drivers/serial/Kconfig.mcux_lpsci \
	/home/riscv/zephyr/drivers/serial/Kconfig.mcux \
	/home/riscv/zephyr/drivers/serial/Kconfig.ns16550 \
	/home/riscv/zephyr/drivers/serial/Kconfig \
	/home/riscv/zephyr/drivers/slip/Kconfig \
	/home/riscv/zephyr/drivers/ethernet/Kconfig.stm32_hal \
	/home/riscv/zephyr/drivers/ethernet/Kconfig.sam_gmac \
	/home/riscv/zephyr/drivers/ethernet/Kconfig.dw \
	/home/riscv/zephyr/drivers/ethernet/Kconfig.mcux \
	/home/riscv/zephyr/drivers/ethernet/Kconfig.enc28j60 \
	/home/riscv/zephyr/drivers/ethernet/Kconfig \
	/home/riscv/zephyr/drivers/console/Kconfig.telnet \
	/home/riscv/zephyr/drivers/console/Kconfig \
	/home/riscv/zephyr/drivers/ieee802154/Kconfig.nrf5 \
	/home/riscv/zephyr/drivers/ieee802154/Kconfig.mcr20a \
	/home/riscv/zephyr/drivers/ieee802154/Kconfig.kw41z \
	/home/riscv/zephyr/drivers/ieee802154/Kconfig.cc2520 \
	/home/riscv/zephyr/drivers/ieee802154/Kconfig \
	/home/riscv/zephyr/drivers/bluetooth/hci/Kconfig \
	/home/riscv/zephyr/drivers/bluetooth/Kconfig \
	/home/riscv/zephyr/drivers/Kconfig \
	/home/riscv/zephyr/kernel/Kconfig.power_mgmt \
	/home/riscv/zephyr/kernel/Kconfig.event_logger \
	/home/riscv/zephyr/kernel/Kconfig \
	/home/riscv/zephyr/boards/arm/96b_nitrogen/Kconfig \
	/home/riscv/zephyr/boards/arm/cc2650_sensortag/Kconfig \
	/home/riscv/zephyr/boards/arm/cc3200_launchxl/Kconfig \
	/home/riscv/zephyr/boards/arm/nrf52840_pca10056/Kconfig \
	/home/riscv/zephyr/boards/arm/nrf52_pca10040/Kconfig \
	/home/riscv/zephyr/boards/x86/galileo/Kconfig \
	/home/riscv/zephyr/boards/xtensa/qemu_xtensa/Kconfig \
	/home/riscv/zephyr/boards/xtensa/xt-sim/Kconfig \
	/home/riscv/zephyr/boards/arc/arduino_101_sss/Kconfig.board \
	/home/riscv/zephyr/boards/arc/em_starterkit/Kconfig.board \
	/home/riscv/zephyr/boards/arc/panther_ss/Kconfig.board \
	/home/riscv/zephyr/boards/arc/quark_se_c1000_ss_devboard/Kconfig.board \
	/home/riscv/zephyr/boards/arm/96b_carbon/Kconfig.board \
	/home/riscv/zephyr/boards/arm/96b_carbon_nrf51/Kconfig.board \
	/home/riscv/zephyr/boards/arm/96b_nitrogen/Kconfig.board \
	/home/riscv/zephyr/boards/arm/arduino_101_ble/Kconfig.board \
	/home/riscv/zephyr/boards/arm/arduino_due/Kconfig.board \
	/home/riscv/zephyr/boards/arm/bbc_microbit/Kconfig.board \
	/home/riscv/zephyr/boards/arm/cc2650_sensortag/Kconfig.board \
	/home/riscv/zephyr/boards/arm/cc3200_launchxl/Kconfig.board \
	/home/riscv/zephyr/boards/arm/cc3220sf_launchxl/Kconfig.board \
	/home/riscv/zephyr/boards/arm/curie_ble/Kconfig.board \
	/home/riscv/zephyr/boards/arm/disco_l475_iot1/Kconfig.board \
	/home/riscv/zephyr/boards/arm/frdm_k64f/Kconfig.board \
	/home/riscv/zephyr/boards/arm/frdm_kl25z/Kconfig.board \
	/home/riscv/zephyr/boards/arm/frdm_kw41z/Kconfig.board \
	/home/riscv/zephyr/boards/arm/hexiwear_k64/Kconfig.board \
	/home/riscv/zephyr/boards/arm/hexiwear_kw40z/Kconfig.board \
	/home/riscv/zephyr/boards/arm/mps2_an385/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nrf51_blenano/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nrf51_pca10028/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nrf51_vbluno51/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nrf52840_pca10056/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nrf52_blenano2/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nrf52_pca10040/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nucleo_f103rb/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nucleo_f334r8/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nucleo_f401re/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nucleo_f411re/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nucleo_f412zg/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nucleo_f413zh/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nucleo_l432kc/Kconfig.board \
	/home/riscv/zephyr/boards/arm/nucleo_l476rg/Kconfig.board \
	/home/riscv/zephyr/boards/arm/olimex_stm32_e407/Kconfig.board \
	/home/riscv/zephyr/boards/arm/olimexino_stm32/Kconfig.board \
	/home/riscv/zephyr/boards/arm/qemu_cortex_m3/Kconfig.board \
	/home/riscv/zephyr/boards/arm/quark_se_c1000_ble/Kconfig.board \
	/home/riscv/zephyr/boards/arm/sam4s_xplained/Kconfig.board \
	/home/riscv/zephyr/boards/arm/sam_e70_xplained/Kconfig.board \
	/home/riscv/zephyr/boards/arm/stm3210c_eval/Kconfig.board \
	/home/riscv/zephyr/boards/arm/stm32373c_eval/Kconfig.board \
	/home/riscv/zephyr/boards/arm/stm32_min_dev/Kconfig.board \
	/home/riscv/zephyr/boards/arm/stm32_mini_a15/Kconfig.board \
	/home/riscv/zephyr/boards/arm/stm32f3_disco/Kconfig.board \
	/home/riscv/zephyr/boards/arm/stm32f469i_disco/Kconfig.board \
	/home/riscv/zephyr/boards/arm/stm32f4_disco/Kconfig.board \
	/home/riscv/zephyr/boards/arm/stm32l496g_disco/Kconfig.board \
	/home/riscv/zephyr/boards/arm/v2m_beetle/Kconfig.board \
	/home/riscv/zephyr/boards/nios2/altera_max10/Kconfig.board \
	/home/riscv/zephyr/boards/nios2/qemu_nios2/Kconfig.board \
	/home/riscv/zephyr/boards/riscv32/artix7_ppu/Kconfig.board \
	/home/riscv/zephyr/boards/riscv32/qemu_riscv32/Kconfig.board \
	/home/riscv/zephyr/boards/riscv32/zedboard_pulpino/Kconfig.board \
	/home/riscv/zephyr/boards/x86/arduino_101/Kconfig.board \
	/home/riscv/zephyr/boards/x86/galileo/Kconfig.board \
	/home/riscv/zephyr/boards/x86/minnowboard/Kconfig.board \
	/home/riscv/zephyr/boards/x86/panther/Kconfig.board \
	/home/riscv/zephyr/boards/x86/qemu_x86/Kconfig.board \
	/home/riscv/zephyr/boards/x86/quark_d2000_crb/Kconfig.board \
	/home/riscv/zephyr/boards/x86/quark_se_c1000_devboard/Kconfig.board \
	/home/riscv/zephyr/boards/x86/tinytile/Kconfig.board \
	/home/riscv/zephyr/boards/xtensa/esp32/Kconfig.board \
	/home/riscv/zephyr/boards/xtensa/qemu_xtensa/Kconfig.board \
	/home/riscv/zephyr/boards/xtensa/xt-sim/Kconfig.board \
	/home/riscv/zephyr/boards/Kconfig \
	/home/riscv/zephyr/arch/xtensa/soc/D_108mini/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/D_212GP/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/D_233L/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/XRC_D2PM_5swIrq/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/XRC_FUSION_AON_ALL_LM/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/esp32/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/hifi2_std/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/hifi3_bd5/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/hifi3_bd5_call0/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/hifi4_bd7/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/hifi_mini/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/hifi_mini_4swIrq/Kconfig.soc \
	/home/riscv/zephyr/arch/xtensa/soc/sample_controller/Kconfig.soc \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_d2000/Kconfig \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_se/Kconfig \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_d2000/Kconfig.soc \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_se/Kconfig.soc \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_x1000/Kconfig.soc \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/Kconfig \
	/home/riscv/zephyr/arch/x86/core/Kconfig \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_d2000/Kconfig.series \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_se/Kconfig.series \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/quark_x1000/Kconfig.series \
	/home/riscv/zephyr/arch/x86/soc/atom/Kconfig.soc \
	/home/riscv/zephyr/arch/x86/soc/ia32/Kconfig.soc \
	/home/riscv/zephyr/arch/x86/soc/intel_quark/Kconfig.soc \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/fe310/Kconfig.soc \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/riscv32-qemu/Kconfig.soc \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/Kconfig \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/fe310/Kconfig.series \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/riscv32-qemu/Kconfig.series \
	/home/riscv/zephyr/arch/riscv32/soc/ppu/Kconfig.soc \
	/home/riscv/zephyr/arch/riscv32/soc/pulpino/Kconfig.soc \
	/home/riscv/zephyr/arch/riscv32/soc/riscv-privilege/Kconfig.soc \
	/home/riscv/zephyr/arch/nios2/soc/nios2-qemu/Kconfig.soc \
	/home/riscv/zephyr/arch/nios2/soc/nios2f-zephyr/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/cc2650/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f1/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f3/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32l4/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/k6x/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kl2x/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kwx/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/sam3x/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/sam4s/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/same70/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/arm/beetle/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/arm/mps2/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/arm/Kconfig \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/Kconfig \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/Kconfig \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/Kconfig \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/Kconfig \
	/home/riscv/zephyr/arch/arm/soc/ti_lm3s6965/Kconfig \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/Kconfig \
	/home/riscv/zephyr/arch/arm/core/cortex_m/mpu/Kconfig \
	/home/riscv/zephyr/arch/arm/core/cortex_m/Kconfig \
	/home/riscv/zephyr/arch/arm/core/Kconfig \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/cc2650/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f1/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f3/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32f4/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/stm32l4/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/k6x/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kl2x/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/kwx/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/sam3x/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/sam4s/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/same70/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/arm/beetle/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/arm/mps2/Kconfig.series \
	/home/riscv/zephyr/arch/arm/soc/arm/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/atmel_sam/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/nordic_nrf5/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/nxp_kinetis/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/st_stm32/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/ti_lm3s6965/Kconfig.soc \
	/home/riscv/zephyr/arch/arm/soc/ti_simplelink/Kconfig.soc \
	/home/riscv/zephyr/arch/arc/soc/quark_se_c1000_ss/Kconfig \
	/home/riscv/zephyr/arch/arc/soc/em11d/Kconfig.soc \
	/home/riscv/zephyr/arch/arc/soc/em7d/Kconfig.soc \
	/home/riscv/zephyr/arch/arc/soc/em9d/Kconfig.soc \
	/home/riscv/zephyr/arch/arc/soc/quark_se_c1000_ss/Kconfig.soc \
	/home/riscv/zephyr/arch/arc/Kconfig \
	/home/riscv/zephyr/arch/arm/Kconfig \
	/home/riscv/zephyr/arch/nios2/Kconfig \
	/home/riscv/zephyr/arch/riscv32/Kconfig \
	/home/riscv/zephyr/arch/x86/Kconfig \
	/home/riscv/zephyr/arch/xtensa/Kconfig \
	/home/riscv/zephyr/arch/Kconfig \
	/home/riscv/zephyr/Kconfig.zephyr \
	Kconfig

include/config/auto.conf: \
	$(deps_config)

ifneq "$(KERNELVERSION)" "1.8.99"
include/config/auto.conf: FORCE
endif

$(deps_config): ;
