
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <toolchain.h>
#include <linker/sections.h>
#include <sw_isr_table.h>

struct _isr_table_entry __sw_isr_table _sw_isr_table[32] = {
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x51000598, (void *)0x500006a4},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50000638},
	{(void *)0x0, (void *)0x50001168},
	{(void *)0x0, (void *)0x50001168},
};
