
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <toolchain.h>
#include <linker/sections.h>
#include <sw_isr_table.h>

struct _isr_table_entry __sw_isr_table _sw_isr_table[32] = {
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x51000698, (void *)0x50000e1c},
	{(void *)0x510006b0, (void *)0x50000848},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x500007d4},
	{(void *)0x0, (void *)0x50001bbc},
	{(void *)0x0, (void *)0x50001bbc},
};
