
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <toolchain.h>
#include <linker/sections.h>
#include <sw_isr_table.h>

struct _isr_table_entry __sw_isr_table _sw_isr_table[32] = {
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x51001ac0, (void *)0x50000950},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x51001acc, (void *)0x50000950},
	{(void *)0x51001b08, (void *)0x500016d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x50000974},
	{(void *)0x0, (void *)0x500055d4},
	{(void *)0x0, (void *)0x500055d4},
};
