
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <toolchain.h>
#include <linker/sections.h>
#include <sw_isr_table.h>

struct _isr_table_entry __sw_isr_table _sw_isr_table[32] = {
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x51000914, (void *)0x50000db0},
	{(void *)0x51000920, (void *)0x50000d80},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50000974},
	{(void *)0x0, (void *)0x50001adc},
	{(void *)0x0, (void *)0x50001adc},
};
